apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-world.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"    
  labels:
{{ include "hello-world.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hello-world.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
