apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inlets.fullname" . }}
  labels:
    {{- include "inlets.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inlets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inlets.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "inlets.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "inlets.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - server
{{- if eq .Values.edition "pro"}}
            - --auto-tls=false
            - --remote-tcp={{ required "A valid .Values.pro.remoteTcp is required" .Values.pro.remoteTcp}}
{{- else }}
            - --print-token
            - --port={{ .Values.service.port}}
  {{- if .Values.community.disableTransportWrapping }}
            - --disable-transport-wrapping
  {{- end }}
{{ end }}
          ports:
            - name: tunnel
              containerPort: {{ .Values.service.port}}
              protocol: TCP
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "inlets.fullname" . }}
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
