apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inlets.fullname" . }}
  labels:
    {{- include "inlets.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.token }}
  token: {{ .Values.token | b64enc | quote }}
  {{- else }}
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
