apiVersion: v1
kind: Service
metadata:
  name: {{ include "okteflix.fullname" . }}-api
  labels:
    {{- include "okteflix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "okteflix.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
