token: 

# community | pro
edition: community

community:
  image: inlets/inlets
  tag: 2.7.0
  disableTransportWrapping: false

pro:
  image: inlets/inlets-pro
  tag: 0.5.6
  remoteTcp: 

replicaCount: 1

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations: 
    dev.okteto.com/generate-host: "true"
  hosts:
    - inlets.local
  tls: []
  
resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
